name: Build (win)

on: [push]

jobs:
  build:

    runs-on: windows-latest
    node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install -g npm-run-all
        npm install -g typescript
        npm install -g tslint
        npm install -g @angular/cli
        npm install

    - name: Start application
      run: npm start

      env:
        CI: true
